### ISSUE TITLE
Canary Analysis fails with java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by raiviskrumins** [spinnaker/kayenta#522] opened 2019-04-11 13:17 UTC
Canary Analysis step fails with attached error:

![Screenshot from 2019-04-11 15-48-17](https://user-images.githubusercontent.com/2749851/55958479-652cb780-5c71-11e9-997d-d9e4ca5a6c2f.png)

**-25916374** canges with every run

It seems that issue is somewhere here:
https://github.com/spinnaker/kayenta/blob/version-0.7.0/kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricSet.java#L118
but I was unable to debug it further with my close-to-none java knowledge.

Prometheus is accessible:
```
2019-04-11 11:35:56.290  INFO 1 --- [    handlers-11] c.n.k.p.service.PrometheusRemoteService  : ---> HTTP GET http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=avg%28requests%7Bversion%3D%22baseline%22%2Chttp_code%3D%22500%22%7D%29&start=2019-04-11T11%3A32%3A53.349Z&end=2019-04-11T11%3A35%3A53.349Z&step=60
2019-04-11 11:35:56.290  INFO 1 --- [    handlers-12] c.n.k.p.service.PrometheusRemoteService  : ---> HTTP GET http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=avg%28requests%7Bversion%3D%22canary%22%2Chttp_code%3D%22500%22%7D%29&start=2019-04-11T11%3A32%3A53.349Z&end=2019-04-11T11%3A35%3A53.349Z&step=60
2019-04-11 11:35:56.311  INFO 1 --- [    handlers-11] c.n.k.p.service.PrometheusRemoteService  : <--- HTTP 200 http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=avg%28requests%7Bversion%3D%22baseline%22%2Chttp_code%3D%22500%22%7D%29&start=2019-04-11T11%3A32%3A53.349Z&end=2019-04-11T11%3A35%3A53.349Z&step=60 (21ms)
2019-04-11 11:35:56.323  INFO 1 --- [    handlers-12] c.n.k.p.service.PrometheusRemoteService  : <--- HTTP 200 http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=avg%28requests%7Bversion%3D%22canary%22%2Chttp_code%3D%22500%22%7D%29&start=2019-04-11T11%3A32%3A53.349Z&end=2019-04-11T11%3A35%3A53.349Z&step=60 (32ms)
```
Data returned from prometheus requests:
```
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1554982493.349,"45"],[1554982553.349,"120"]]}]}}
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1554982493.349,"124"],[1554982553.349,"288"]]}]}}
```
Cannary config:
```{
  "applications": [
    "sampleapp"
  ],
  "classifier": {
    "groupWeights": {
      "Group 1": 100
    },
    "scoreThresholds": {
      "marginal": 75,
      "pass": 95
    }
  },
  "configVersion": "1",
  "createdTimestamp": 1554874876568,
  "createdTimestampIso": "2019-04-10T05:41:16.568Z",
  "description": "",
  "judge": {
    "judgeConfigurations": {},
    "name": "NetflixACAJudge-v1.0"
  },
  "metrics": [
    {
      "analysisConfigurations": {
        "canary": {
          "direction": "increase",
          "nanStrategy": "replace"
        }
      },
      "groups": [
        "Group 1"
      ],
      "name": "error_rate",
      "query": {
        "customFilterTemplate": "http_code",
        "labelBindings": [
          "http_code=\"500\""
        ],
        "metricName": "requests",
        "serviceType": "prometheus",
        "type": "prometheus"
      },
      "scopeName": "default"
    }
  ],
  "name": "kayenta-test",
  "templates": {
    "http_code": "version=\"${scope}\""
  },
  "updatedTimestamp": 1554968424991,
  "updatedTimestampIso": "2019-04-11T07:40:24.991Z"
}
```

Spinnaker version: 1.13.3
Kayenta version: gcr.io/spinnaker-marketplace/kayenta:0.7.0-20190315122808
Prometheus version: 2.7.2

```
2019-04-11 11:35:57.167  WARN 1 --- [    handlers-20] c.n.s.o.e.DefaultExceptionHandler        : Error occurred during task metricSetMixer

java.lang.IllegalArgumentException: -25916374
	at java.util.stream.DoublePipeline.limit(DoublePipeline.java:338) ~[na:1.8.0_191]
	at com.netflix.kayenta.metrics.MetricSetMixerService.makeTemplate(MetricSetMixerService.java:153) ~[kayenta-core.jar:na]
	at com.netflix.kayenta.metrics.MetricSetMixerService.mixOneMetric(MetricSetMixerService.java:138) ~[kayenta-core.jar:na]
	at com.netflix.kayenta.metrics.MetricSetMixerService.mixAll(MetricSetMixerService.java:197) ~[kayenta-core.jar:na]
	at com.netflix.kayenta.metrics.orca.MetricSetMixerServiceTask.execute(MetricSetMixerServiceTask.java:110) ~[kayenta-core.jar:na]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:100) ~[orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:56) ~[orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withLoggingContext(RunTaskHandler.kt:316) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$withLoggingContext(RunTaskHandler.kt:56) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:99) ~[orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:56) ~[orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt) ~[orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:97) ~[kork-security-3.9.2.jar:3.9.2]
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:49) ~[orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:56) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:98) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:56) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:182) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:56) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:49) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:33) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:59) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:33) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:68) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:56) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:55) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:56) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:42) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:56) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:175) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:69) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:56) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36) [keiko-core-2.9.8.jar:2.9.8]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:56) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:47) [orca-queue-6.139.0.jar:6.139.0]
	at com.netflix.spinnaker.q.QueueProcessor$pollOnce$1$1.run(QueueProcessor.kt:82) [keiko-core-2.9.8.jar:2.9.8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
```

**Comment by NikhilaKambham** [comment] 2019-04-11 17:26
If it helps, I saw this issue as well in the new release 1.31.1, so we reverted back to an older version.

**Comment by miaowukong** [comment] 2019-04-16 09:03
https://github.com/spinnaker/kayenta/issues/524

**Comment by fieldju** [comment] 2019-04-16 16:28
@spinnakerbot assign-issue @fieldju

**Comment by fieldju** [comment] 2019-04-16 16:29
This is a duplicate of #524, im going to try to take the examples from both these issues and see if I can write a test that reproduces the issue then TDD a fix.

**Comment by fieldju** [comment] 2019-04-16 19:35
![image](https://user-images.githubusercontent.com/711726/56238734-0043d980-6044-11e9-8fd6-9fc979de053d.png)

I have a test that reproduces the issue, now to see if it is an obvious / easy fix.

**Comment by skandragon** [comment] 2019-04-18 22:30
duplicate of #524

**Closed** 2019-04-18 22:30 UTC
